services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ExpenseTracker'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: